import { DetailShell } from "../../detail-shell";

export default function ComponentsPage() {
  return <DetailShell eyebrow="CORE COMPONENTS" title="Control the interfaces that control performance." intro="EST Solution connects catalyst, MEA, membrane, Ti-PTL and stack development to reduce iteration time and dependence on imported components.">
    <div className="detail-content">
      <section className="detail-intro"><h2>One technical chain, developed together.</h2><p>Water-electrolysis performance depends on many closely coupled layers. Treating them as a connected system makes it possible to tune catalyst loading, electrochemical activity, gas transport, membrane durability and stack architecture around the same application goal.</p></section>
      <section className="detail-section"><div className="eyebrow"><span /> COMPONENT PLATFORM</div><h2>Five areas of in-house development.</h2><div className="feature-grid"><article><small>CATALYST</small><h3>Low precious-metal loading</h3><p>High-activity catalyst development focused on lowering expensive material use.</p></article><article><small>MEA</small><h3>Large-area manufacturing</h3><p>High-current-density MEA work with reported manufacturing yield of approximately 87%.</p></article><article><small>MEMBRANE</small><h3>Performance and durability</h3><p>Hydrocarbon membrane development aimed at low hydrogen crossover and longer operating life.</p></article><article><small>TI-PTL</small><h3>Controlled pore structure</h3><p>Porous transport-layer engineering designed to improve contact and transport at the catalyst layer.</p></article><article><small>STACK</small><h3>Customized architecture</h3><p>Component selection and geometry tailored to the required capacity and operating environment.</p></article><article><small>INTEGRATION</small><h3>Shorter iteration cycles</h3><p>Shared development feedback from material testing through system performance.</p></article></div></section>
      <section className="detail-media"><img src="/ti-ptl-diagram.png" alt="Comparison of large-pore and multi-scale porous titanium transport layers" /><div className="detail-media-copy"><div className="eyebrow"><span /> TI-PTL CONCEPT</div><h2>Transport where it matters.</h2><p>A tailored mix of pore sizes can improve the interface between the titanium transport layer and catalyst layer. This supports more controlled gas and water transport than a uniform large-pore structure.</p></div></section>
      <p className="results-note">Performance and yield figures are brochure-reported development results and require confirmation for a specific commercial configuration.</p>
    </div>
  </DetailShell>;
}
